name: sqflite_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  barcode_scan: ^3.0.1
  cupertino_icons: ^0.1.3
  email_validator: ^1.0.6
  equatable: ^1.2.5
  flappy_search_bar: ^1.7.2
  flutter_bloc: ^6.0.5
  flutter_html: ^1.0.2
  flutter_package_manager: ^0.2.0
  flutter_wordpress: ^0.2.1
  get: ^3.12.1
  get_it: ^4.0.4
  http: ^0.12.2
  intl: ^0.16.1
  loading: ^1.0.2
  provider: ^4.3.2
  speech_to_text: ^2.7.0
  sqflite: ^1.3.1
  url_launcher: ^5.7.2
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/locale/localization_en.json
    - assets/locale/localization_hi.json
    - assets/locale/localization_pt.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
